# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  company_repository:
    class: AppBundle\Infrastructure\Repositories\CompanyRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Company
  company_service:
    class: AppBundle\Domain\Services\CompanyService
    arguments: ["@company_repository"]
